/**
 * Phase 14.5 — Document Generator
 * Generate PDF, DOCX, Excel, CSV, Markdown, HTML, TXT, JSON from any content.
 * One-click export for any AI response.
 */

import { Logger } from "../system/Logger";

export type ExportFormat = "pdf" | "docx" | "xlsx" | "csv" | "md" | "html" | "txt" | "json";

export interface ExportRequest {
  content: string;
  format: ExportFormat;
  filename?: string;
  title?: string;
  metadata?: Record<string, any>;
}

export interface ExportResult {
  blob: Blob;
  filename: string;
  format: ExportFormat;
  size: number;
}

export class DocumentGenerator {
  /**
   * Export content to the specified format and trigger download.
   */
  static async export(request: ExportRequest): Promise<ExportResult> {
    Logger.info(`[DocumentGenerator] Exporting as ${request.format}`);

    const filename = request.filename || `omni-export-${Date.now()}`;

    switch (request.format) {
      case "txt":
        return this.exportTXT(request, filename);
      case "md":
        return this.exportMarkdown(request, filename);
      case "json":
        return this.exportJSON(request, filename);
      case "html":
        return this.exportHTML(request, filename);
      case "csv":
        return this.exportCSV(request, filename);
      case "pdf":
        return this.exportPDF(request, filename);
      case "docx":
        return this.exportDOCX(request, filename);
      case "xlsx":
        return this.exportXLSX(request, filename);
      default:
        return this.exportTXT(request, filename);
    }
  }

  /**
   * Export and immediately trigger browser download.
   */
  static async download(request: ExportRequest): Promise<void> {
    const result = await this.export(request);
    this.triggerDownload(result.blob, result.filename);
  }

  private static exportTXT(request: ExportRequest, filename: string): ExportResult {
    const blob = new Blob([request.content], { type: "text/plain;charset=utf-8" });
    return { blob, filename: `${filename}.txt`, format: "txt", size: blob.size };
  }

  private static exportMarkdown(request: ExportRequest, filename: string): ExportResult {
    const blob = new Blob([request.content], { type: "text/markdown;charset=utf-8" });
    return { blob, filename: `${filename}.md`, format: "md", size: blob.size };
  }

  private static exportJSON(request: ExportRequest, filename: string): ExportResult {
    let jsonContent: string;
    try {
      // Try to parse as JSON first
      const parsed = JSON.parse(request.content);
      jsonContent = JSON.stringify(parsed, null, 2);
    } catch {
      // Wrap in a JSON object
      jsonContent = JSON.stringify(
        {
          title: request.title || "Omni One Export",
          content: request.content,
          exportedAt: new Date().toISOString(),
          metadata: request.metadata || {},
        },
        null,
        2
      );
    }
    const blob = new Blob([jsonContent], { type: "application/json;charset=utf-8" });
    return { blob, filename: `${filename}.json`, format: "json", size: blob.size };
  }

  private static exportHTML(request: ExportRequest, filename: string): ExportResult {
    // Convert markdown-like content to HTML
    const htmlContent = this.markdownToHTML(request.content);
    const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${request.title || "Omni One Export"}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }
    h1, h2, h3 { color: #1a1a2e; }
    code { background: #f4f4f4; padding: 0.2em 0.4em; border-radius: 3px; font-family: monospace; }
    pre { background: #f4f4f4; padding: 1rem; border-radius: 6px; overflow-x: auto; }
    pre code { background: none; padding: 0; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f0f0f0; }
    blockquote { border-left: 4px solid #7c3aed; margin: 0; padding-left: 1rem; color: #555; }
    .meta { color: #888; font-size: 0.85rem; margin-bottom: 2rem; }
  </style>
</head>
<body>
  ${request.title ? `<h1>${request.title}</h1>` : ""}
  <div class="meta">Generated by Omni One • ${new Date().toLocaleString()}</div>
  <div class="content">${htmlContent}</div>
</body>
</html>`;
    const blob = new Blob([fullHTML], { type: "text/html;charset=utf-8" });
    return { blob, filename: `${filename}.html`, format: "html", size: blob.size };
  }

  private static exportCSV(request: ExportRequest, filename: string): ExportResult {
    // Try to detect tables in the content
    const lines = request.content.split("\n");
    const csvLines: string[] = [];

    for (const line of lines) {
      if (line.includes("|")) {
        // Markdown table row
        const cells = line
          .split("|")
          .map((c) => c.trim())
          .filter((c) => c && !c.match(/^[-:]+$/));
        if (cells.length > 0) {
          csvLines.push(cells.map((c) => `"${c.replace(/"/g, '""')}"`).join(","));
        }
      } else if (line.trim()) {
        csvLines.push(`"${line.trim().replace(/"/g, '""')}"`);
      }
    }

    const csvContent = csvLines.join("\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8" });
    return { blob, filename: `${filename}.csv`, format: "csv", size: blob.size };
  }

  private static async exportPDF(request: ExportRequest, filename: string): Promise<ExportResult> {
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth() - 2 * margin;
      let y = margin;

      // Title
      if (request.title) {
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text(request.title, margin, y);
        y += 10;
      }

      // Metadata
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by Omni One • ${new Date().toLocaleString()}`, margin, y);
      y += 8;
      doc.setTextColor(0, 0, 0);

      // Content
      doc.setFontSize(11);
      const lines = doc.splitTextToSize(request.content, pageWidth);

      for (const line of lines) {
        if (y > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }

        // Detect headers
        if (line.startsWith("# ")) {
          doc.setFontSize(16);
          doc.setFont("helvetica", "bold");
          doc.text(line.replace(/^#+\s/, ""), margin, y);
          doc.setFontSize(11);
          doc.setFont("helvetica", "normal");
        } else if (line.startsWith("## ")) {
          doc.setFontSize(14);
          doc.setFont("helvetica", "bold");
          doc.text(line.replace(/^#+\s/, ""), margin, y);
          doc.setFontSize(11);
          doc.setFont("helvetica", "normal");
        } else if (line.startsWith("**") && line.endsWith("**")) {
          doc.setFont("helvetica", "bold");
          doc.text(line.replace(/\*\*/g, ""), margin, y);
          doc.setFont("helvetica", "normal");
        } else {
          doc.text(line, margin, y);
        }
        y += 6;
      }

      const pdfBlob = doc.output("blob");
      return { blob: pdfBlob, filename: `${filename}.pdf`, format: "pdf", size: pdfBlob.size };
    } catch (error) {
      Logger.error("[DocumentGenerator] PDF export failed", { error });
      // Fallback to HTML
      const htmlResult = this.exportHTML(request, filename);
      return { ...htmlResult, format: "pdf" };
    }
  }

  private static async exportDOCX(
    request: ExportRequest,
    filename: string
  ): Promise<ExportResult> {
    try {
      const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import("docx");

      const paragraphs: InstanceType<typeof Paragraph>[] = [];

      if (request.title) {
        paragraphs.push(
          new Paragraph({
            text: request.title,
            heading: HeadingLevel.TITLE,
          })
        );
      }

      // Add metadata
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by Omni One • ${new Date().toLocaleString()}`,
              color: "888888",
              size: 18,
            }),
          ],
        })
      );

      // Parse content into paragraphs
      const lines = request.content.split("\n");
      for (const line of lines) {
        if (!line.trim()) {
          paragraphs.push(new Paragraph({ text: "" }));
          continue;
        }

        if (line.startsWith("# ")) {
          paragraphs.push(
            new Paragraph({ text: line.replace(/^#+\s/, ""), heading: HeadingLevel.HEADING_1 })
          );
        } else if (line.startsWith("## ")) {
          paragraphs.push(
            new Paragraph({ text: line.replace(/^#+\s/, ""), heading: HeadingLevel.HEADING_2 })
          );
        } else if (line.startsWith("### ")) {
          paragraphs.push(
            new Paragraph({ text: line.replace(/^#+\s/, ""), heading: HeadingLevel.HEADING_3 })
          );
        } else if (line.startsWith("- ") || line.startsWith("* ")) {
          paragraphs.push(
            new Paragraph({
              text: line.replace(/^[-*]\s/, ""),
              bullet: { level: 0 },
            })
          );
        } else {
          // Handle bold text
          const boldRegex = /\*\*(.*?)\*\*/g;
          const children: InstanceType<typeof TextRun>[] = [];
          let lastIndex = 0;
          let match;

          while ((match = boldRegex.exec(line)) !== null) {
            if (match.index > lastIndex) {
              children.push(new TextRun({ text: line.slice(lastIndex, match.index) }));
            }
            children.push(new TextRun({ text: match[1], bold: true }));
            lastIndex = match.index + match[0].length;
          }

          if (lastIndex < line.length) {
            children.push(new TextRun({ text: line.slice(lastIndex) }));
          }

          paragraphs.push(
            children.length > 0
              ? new Paragraph({ children })
              : new Paragraph({ text: line })
          );
        }
      }

      const doc = new Document({ sections: [{ properties: {}, children: paragraphs }] });
      const buffer = await Packer.toBlob(doc);
      return { blob: buffer, filename: `${filename}.docx`, format: "docx", size: buffer.size };
    } catch (error) {
      Logger.error("[DocumentGenerator] DOCX export failed", { error });
      return this.exportTXT(request, filename);
    }
  }

  private static async exportXLSX(
    request: ExportRequest,
    filename: string
  ): Promise<ExportResult> {
    try {
      const { utils, write } = await import("xlsx");

      // Parse tables from content
      const lines = request.content.split("\n");
      const tableRows: string[][] = [];
      let inTable = false;

      for (const line of lines) {
        if (line.includes("|")) {
          const cells = line
            .split("|")
            .map((c) => c.trim())
            .filter((c) => c && !c.match(/^[-:]+$/));
          if (cells.length > 0) {
            tableRows.push(cells);
            inTable = true;
          }
        } else if (inTable && line.trim()) {
          tableRows.push([line.trim()]);
        } else if (!line.trim()) {
          inTable = false;
        }
      }

      // If no tables found, create a simple sheet with the content
      const sheetData =
        tableRows.length > 0
          ? tableRows
          : request.content.split("\n").map((line) => [line]);

      const ws = utils.aoa_to_sheet(sheetData);
      const wb = utils.book_new();
      utils.book_append_sheet(wb, ws, "Export");

      const buffer = write(wb, { bookType: "xlsx", type: "array" });
      const blob = new Blob([buffer], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      return { blob, filename: `${filename}.xlsx`, format: "xlsx", size: blob.size };
    } catch (error) {
      Logger.error("[DocumentGenerator] XLSX export failed", { error });
      return this.exportCSV(request, filename);
    }
  }

  private static markdownToHTML(markdown: string): string {
    return markdown
      .replace(/^### (.*$)/gm, "<h3>$1</h3>")
      .replace(/^## (.*$)/gm, "<h2>$1</h2>")
      .replace(/^# (.*$)/gm, "<h1>$1</h1>")
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .replace(/`(.*?)`/g, "<code>$1</code>")
      .replace(/```[\s\S]*?```/g, (match) => {
        const code = match.replace(/```\w*\n?/, "").replace(/```$/, "");
        return `<pre><code>${code}</code></pre>`;
      })
      .replace(/^- (.*$)/gm, "<li>$1</li>")
      .replace(/(<li>.*<\/li>)/s, "<ul>$1</ul>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/^(?!<[h|u|l|p|b|c])(.*$)/gm, "<p>$1</p>")
      .replace(/<p><\/p>/g, "");
  }

  private static triggerDownload(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
